### ISSUE TITLE
mojave-xcode-10.3 not starting

### ISSUE THREAD

**Issue by budde377** [cirruslabs/osx-images#12]
I've been trying to use the `mojave-xcode-10.3` image in my builds, but they won't seem to start. Also, I've noted that the image isn't listed on the official documentation. Aren't the image supported yet, and if so, when can we expect it to be 😄

**Comment by fkorotkov** [comment]
Hey @budde377, Xcode 10.3 was released after Xcode 11 Betas started coming out so we were only building `mojave-xcode-11`. Xcode 10.3 looked like a very minor update. Is there something particular that you are missing?

**Comment by budde377** [comment]
@fkorotkov No, it would seem that the `mojave-xcode-10.2` image is actually doing the trick. I'll close this issue.
