### ISSUE TITLE
WebDriver not working in mojave-base when it worked in high-sierra-base

### ISSUE THREAD

**Issue by KronicDeth** [cirruslabs/osx-images#14]
Build that were auto-upgraded from `high-sierra-base` to `mojave-base` or with an updated `.cirrus.yml` are stuck with the following prompt:

```
{"value":{"error":"session not created","message":"Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver.","stacktrace":""}}
error: test failed, to rerun pass '--test web'
```

https://cirrus-ci.com/task/4760821944549376?command=lumen_web_test#L260

The `.cirrus.yml` already contained `sudo safaridriver --enable` calls, which [do succeed](https://cirrus-ci.com/task/4760821944549376?command=enable_safari_driver#L0), but unlike on `high-sierra-base`, this is not enough to get Safari working with Web Driver.

Can you enable some setting in the image to fix this?

**Comment by fkorotkov** [comment]
Sorry to hear about the regression! Quick Googling doesn't show how to automate setting `Allow Remote Automation` via command line. Will investigate further to see how to modify the recipes for the images.

**Comment by fkorotkov** [comment]
I wasn't able to find a viable way to automate this configuration. I prefer not to modify the VMs manually so not sure what to do here. How crucial for you testing on Safari?

**Comment by KronicDeth** [comment]
We’re running the macOS VMs specifically to get WebAssembly testing in Safari.  There’s not really a point for the macOS builds without it for us until we start using the macOS build to create precompiled binaries, which isn’t for a 4-6 weeks.

**Comment by fkorotkov** [comment]
Got it. Just manually modified the VM. Please try to re-enable the tests again.

**Comment by KronicDeth** [comment]
The build (https://cirrus-ci.com/task/5356567184015360) is fixed (https://github.com/lumen/lumen/pull/319).  Thanks @fkorotkov.
