### ISSUE TITLE
Catalina support?

### ISSUE THREAD

**Issue by lassik** [cirruslabs/osx-images#18]
If I understood correctly, you are using Anka for MacOS build containers. There's now a Catalina beta: https://ankadoc.bitbucket.io/#macos-version-support-for-anka-build-anka-flow-and-anka-secure

Could we have it in CIrrus soon?

**Comment by fkorotkov** [comment]
Hopefully we'll get that by December 2nd. Right now there is a lot of updates happening to the underlying infrastructure to make it possible to have Catalina.

**Comment by lassik** [comment]
Awesome! Thanks for the status update.

**Comment by fkorotkov** [comment]
Catalina VMs have been available for a while
