### ISSUE TITLE
Installing Gem Fails With Permission Error

### ISSUE THREAD

**Issue by sanssecours** [cirruslabs/osx-images#19]
👋 Hi,

first I would like to thank you for offering your great CI service for FLOSS software for free. It works really well and is quite fast too. After this round of well deserved praise 😊, it is probably time to write about the problem I noticed with some of the recent changes to the macOS images.

It seems like it is no longer possible to install Ruby gems with the Homebrew’s version of Ruby. I created a project that shows this problem [here](https://github.com/sanssecours/Test-Cirrus). As you can see in the [log file](https://cirrus-ci.com/task/4806805401632768?command=install#L15), the command `gem install` fails with a file permission error:

```
#<Thread:0x00007fc9e9a8ebb0@/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/ronn-0.7.3.gem (Errno::EACCES)
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `open'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `write_binary'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:315:in `cache_update_path'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:159:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
#<Thread:0x00007fc9e9a8ef20@/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/mustache-1.1.0.gem (Errno::EACCES)
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `open'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:873:in `write_binary'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:315:in `cache_update_path'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:159:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/mustache-1.1.0.gem
```

The installation even fails with this permission error if I [use the option `--user-install`](https://cirrus-ci.com/task/5178608036872192). 

Another minor problem I noticed is the banner “High Sierra images were deprecated! Auto upgraded to mojave-xcode-11.2.1”. This message seems rather strange, since `cirrus.yml` already [specifies a macOS Mojave image](https://github.com/sanssecours/Test-Cirrus/blob/1899d2f2363292a319f9c498f59c9b28e0f39661/.cirrus.yml#L7).

**Comment by fkorotkov** [comment]
Hey @sanssecours, there was a change to switch from the pre-installed version of ruby that comes with Mojave to the latest by installing it with brew.  Seems like you'll need to use `sudo` in order to globally install things in `/usr/local/lib/ruby/`. See https://github.com/sanssecours/Test-Cirrus/pull/1

**Comment by fkorotkov** [comment]
BTW sorry for the false warning message. Your task was upgrade from `mojave-xcode-11.1` to `mojave-xcode-11.2.1`. No High Sierra involved.

**Comment by sanssecours** [comment]
> Hey @sanssecours, there was a change to switch from the pre-installed version of ruby that comes with Mojave to the latest by installing it with brew. Seems like you'll need to use `sudo` in order to globally install things in `/usr/local/lib/ruby/`.

Thank you for the information. I still do wonder why using `--user-install` requires superuser privileges. It worked before without `sudo`. Anyway, thank you for the quick and helpful answer 💖.
