### ISSUE TITLE
Latest Flutter stable release

### ISSUE THREAD

**Issue by MaikuB** [cirruslabs/osx-images#20]
Have a plugin where the build requires the latest stable Flutter SDK (1.10.0) and builds are currently failing is the images are using the previous stable release? Any chance of the image will be updated soon or is that part of looking to supporting Catalina?

**Comment by fkorotkov** [comment]
There is underlying work is happening to migrate to new macOS infrastructure with Catalina support. The upgrade also includes better network and some simplifications for us to such upgrade in the future. The new infrastructure is not quite ready to handle all the current builds so I've updated the current images and documented in https://github.com/cirruslabs/cirrus-ci-docs/commit/af106a8a0539292d3c46bf3a7a8a2911ebd18712
