### ISSUE TITLE
Catalina-flutter image ships with xcode11.3 & 11.4 but defaults to 11.3

### ISSUE THREAD

**Issue by ened** [cirruslabs/osx-images#22]
One of the warning messages as they fly by mentions /Applications/Xcode-11.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk.

This is different than my expectation that the Catalina-flutter image uses Xcode 11.4. 

I think the image should on boot run "xcode-select -s /Applications/Xcode-11.4.app", or get rid of the old Xcode version?

**Comment by ened** [comment]
Actually, the Catalina-flutter images do not ship with Xcode 11.4 at all!

```
ls -la /Applications
total 16
drwxrwxr-x+  8 root  admin   256 Jan 16 09:22 .
drwxr-xr-x  22 root  admin   704 Jan 16 07:59 ..
-rw-rw-r--   1 root  admin  6148 Jan 16 15:30 .DS_Store
-rw-r--r--   1 root  wheel     0 Nov  9 02:03 .localized
drwxr-xr-x@  3 root  wheel    96 Nov 11 21:44 Safari.app
drwxr-xr-x   4 root  wheel   128 Dec  5 00:23 Utilities
drwxr-xr-x   3 anka  staff    96 Dec 18 23:42 Xcode-11.3.1.app
lrwxr-xr-x   1 root  admin    30 Jan 16 09:22 Xcode.app -> /Applications/Xcode-11.3.1.app
```

**Comment by fkorotkov** [comment]
Yeah, it still points to `catalina-xcode-11.3.1-flutter`, changing `catalina-flutter` alias to point to `catalina-xcode-11.4-flutter` right now

**Comment by ened** [comment]
@fkorotkov thank you for helping out so quickly! The repository is a great way to see how the images are build. Do you think it's possible keep a up2date list of "available" (past & present) image names somewhere, e.g. on the doc website. And also link to it from the OS X-images README file. Would have saved a bit of time.

**Comment by ened** [comment]
Btw, switching to the *catalina-xcode-11.4-flutter* image, results in xcodebuild not found:

```
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
```

**Comment by fkorotkov** [comment]
@ened which command are you running?

**Comment by ened** [comment]
@fkorotkov `flutter doctor -v`

**Comment by fkorotkov** [comment]
@ened could you please try again with `catalina-xcode-11.4-flutter`? Note that it will take a while to started executing after scheduling since not all physical nodes have the new VM cached.

**Comment by ened** [comment]
Yup, it works fine now. Thank you very much.

**Comment by ened** [comment]
@fkorotkov is the catalina-flutter image switched yet? Seems like still xcode11.3

**Comment by fkorotkov** [comment]
Planning to switch later today
