### ISSUE TITLE
Xcode 11.4.1

### ISSUE THREAD

**Issue by ened** [cirruslabs/osx-images#23]
Xcode 11.4.1 has just been released. Could the Catalina images be upgraded?

**Comment by ened** [comment]
I saw the 11.4.1 image being commit, so gave it a go. It seems the OS X instance won't start yet. Reverting to 11.4...

**Comment by fkorotkov** [comment]
11.4.1 images are available now. Feel free to try them out!

**Comment by ened** [comment]
Something is not right with the 11.4.1 images. I get 3 (out of 8) "instance failed to start" messages with it.

**Comment by fkorotkov** [comment]
But the ones stated worked OK?

**Comment by ened** [comment]
It actually seems to have "recovered", so may not have been related to the 11.4.1 version after all. I restarted the failed jobs and all went through.
Thank you, case closed.
