### ISSUE TITLE
Latest Flutter/Dart versions (Flutter 1.17.0/Dart 2.8.1)

### ISSUE THREAD

**Issue by sderungs99** [cirruslabs/osx-images#25]
When will the osx-image be updated with the latest Flutter and Dart versions?

**Comment by fkorotkov** [comment]
It should be available now in `catalina-flutter` aka `catalina-xcode-11.4.1-flutter`. Note that for the next few hours it may take a bit longer to schedule these images since the new image is slowly distributing to all the nodes.
