### ISSUE TITLE
Make LCOV a part of the osx-image?

### ISSUE THREAD

**Issue by sderungs99** [cirruslabs/osx-images#26]
Is it possible to have LCOV installed on the image?

http://ltp.sourceforge.net/coverage/lcov.php

**Comment by fkorotkov** [comment]
It seems you can also install is with `brew`. Will it work for you?

**Comment by sderungs99** [comment]
Yeah, I can try that. I was hoping it could be part of the base as LCOV seems to be part of the base image for cirrusci/flutter:latest as well, if I’m not wrong?

**Comment by sderungs99** [comment]
Tested it and works fine. It also only takes a few seconds to install it.

Example for reference:
add_lcov_script:
    - brew install lcov
