### ISSUE TITLE
Make AppleSimulatorUtils a part of the OSX image

### ISSUE THREAD

**Issue by sderungs99** [cirruslabs/osx-images#27]
Is it possible to make applesimutils a part of the OSX image?

https://github.com/wix/AppleSimulatorUtils

Our use case for this is that for our Flutter UI tests we need to accept/decline location tracking, which is not possible to do programmatically without applesimutils.

**Comment by fkorotkov** [comment]
You can install it via `brew` inside the VM. We are very conservative about additing more tools to the base image since you'll never cover all the use cases but a burden of maintaining recent versions is real. 😅

**Comment by sderungs99** [comment]
Fully understand! Let me give it a try to install on the VM, if I get some time this weekend :-) I will report the results back here...

**Comment by sderungs99** [comment]
Works fine. Here is what I am doing, for reference:

add_applesimutils_script:
  - brew tap wix/brew
  - brew install applesimutils
