### ISSUE TITLE
Latest Flutter version

### ISSUE THREAD

**Issue by sderungs99** [cirruslabs/osx-images#29]
Hi,

When will the images be updated with the latest available flutter version?

Regards,
Sascha

**Comment by fkorotkov** [comment]
Hey @sderungs99, probably today or tomorrow once Xcode 12.2 is released. In the meantime you can run `flutter upgrade` just to make sure you are getting the latest Flutter version.

**Comment by sderungs99** [comment]
Thank you!

Related to this, it looks like Cocoapods is also not yet upgraded to the latest version. Should I upgrade that as well via my script? Or are you also planning to update this soon?

**Comment by fkorotkov** [comment]
Yeah, the new VM version will get all the gems and brew packages updates as well.

**Comment by sderungs99** [comment]
Awesome. Can we keep this issue open until the new image is a available?

**Comment by fkorotkov** [comment]
The image with Xcode 12.1 got update. In the meantime working on Big Sur VMs with Xcode 12.2.
