### ISSUE TITLE
macOS image with Android SDK bundled?

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/osx-images#3]
Similar request to https://github.com/cirruslabs/docker-images-windows/issues/3 - if we could have Android SDK pre-bundled here it would help with some integration tests I want to write.  Otherwise I'd have to pull it down and try to cache it.

**Comment by fkorotkov** [comment]
I'm actually working on a VM with Flutter pre-installed. Can include Android SDK as well!

But first need to make a Homebrew formula that works. Formulas in https://github.com/flutter/flutter/issues/14050 don't quite work, you can't change channel if you are using them.

**Comment by dnfield** [comment]
Nice!

In this case, I wouldn't want flutter installed, just the Android SDK.  Part of the test would be pulling flutter down

**Comment by fkorotkov** [comment]
Will it be ok to have Flutter pre-installed though? macOS VMs uses layers but they are still pretty huge, don't want to create too many of them.

**Comment by dnfield** [comment]
Should be fine

**Comment by dnfield** [comment]
You might have an easier time just doing git clone (maybe single branch) followed by flutter precache
