### ISSUE TITLE
Command Line Tools outdated

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/osx-images#30]
Can we get a catalina-xcode-12.3 image?

My use case is running valgrind (https://github.com/LouisBrunner/valgrind-macos) which is pretty fragile when it comes to versions. I currently use catalina-base and install Apple's "Command Line Tools" manually but that's a PITA in CI because the normal process involves the user clicking on buttons see https://apple.stackexchange.com/a/195963 .

A catalina-xcode-12.3 image should do the job. valgrind compiles fine on big-sur-xcode-12.3. But I can switch to big-sur because valgrind just won't run work there properly, it's not supported yet.

**Comment by fkorotkov** [comment]
`catalina-base` should have the command line tools installed. But probably not the latest. Will an update to `catalina-base` work for you?

**Comment by real-or-random** [comment]
Indeed, they're available (because installing homebrew automatically installs command line tools AFAIU) but not in the latest version.

> Will an update to catalina-base work for you?

I believe this will do the job, too.

**Comment by real-or-random** [comment]
Ok, and with homebrew in mind , I can imagine that even a simple rebuild of `catalina-base` should work because then homebrew should fetch the newest version of CLT.

**Comment by fkorotkov** [comment]
Let's try that first. The VM hasn't been rebuilt since October. If that won't work then I'll build the Xcode one of the update version. Will ping you once available.

**Comment by fkorotkov** [comment]
Sorry it's taking a little bit of time. I want to include the latest security updates for Catalina in the VM and the VM just keeps hanging. I'm investigating it...

**Comment by real-or-random** [comment]
Thanks for the quick reply and no worries, it's not the urgent because the manual installation works. And have a merry Christmas!

**Comment by fkorotkov** [comment]
BTW how do you update the CMD Tools manually? Though `softwareupdates`?

**Comment by real-or-random** [comment]
See https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line/195963 (and the comment including a change for catalina). It's implemented here: https://github.com/real-or-random/secp256k1/blob/1111e4801e88f605a2eb9839752ce68e40a14641/.cirrus.yml#L115

**Comment by fkorotkov** [comment]
The image should be updated now. 👌
