### ISSUE TITLE
fastlane command not found

### ISSUE THREAD

**Issue by sderungs99** [cirruslabs/osx-images#35]
Is fastlane not installed anymore on big-sur-xcode-NN? My pipeline is failing when I want to execute a fastlane script with `/var/folders/sr/b58hwhtj0jbcf4r09zmg0wlc0000gn/T/scriptsc67cf22746e995af5a25367951baa2ff.sh: line 7: fastlane: command not found`

This used to work until recently, so maybe something has changed?

**Comment by fkorotkov** [comment]
If I recall correctly we removed it because fastlane is updating too frequently and we were not able to keep it up-to-date because the VMs are updated once a new Xcode is released.

**Comment by fkorotkov** [comment]
Once Xcode 12.5 will be available the new VM will contain pre-installed fastlane.

**Comment by sderungs99** [comment]
Is there any best practice for the time being how to use fastlane, while it is not pre-installed? any examples how to install it as part of my own script?

**Comment by fkorotkov** [comment]
You can run 'brew install fastlane'. Sorry for the inconvenience! It's taking unusually long for Apple to release GA Xcode 12.5. They've already had 3 betas. 😥
