### ISSUE TITLE
Intermittent monterey-xcode-13.2 failures when starting up VMs

### ISSUE THREAD

**Issue by ibuclaw** [cirruslabs/osx-images#43]
> Persistent worker failed to start the task:
> Parallels isolation failed: failed to create VM cloned from "monterey-xcode-13.2": Parallels VM operation failed: failed to clone VM "cirrus-5b4fe44b-3170-4198-8d0b-9f5dea734084": Parallels command returned non-zero exit code: "Failed to clone the VM: Unable to perform the operation because \"monterey-xcode-13.2\" is in the intermediate state. Unpacking \"/Users/administrator/Parallels/monterey-xcode-13.2.pvmi/config.pvsp\" has been started but not finished yet. Please finish unpacking."

This occurs from time to time, and regularly enough to be noticeable/remembered.

**Comment by fkorotkov** [comment]
Could you please provide links to failing tasks. Seems one of the workers is in a bad state.

**Comment by ibuclaw** [comment]
https://cirrus-ci.com/task/5595194593640448
https://cirrus-ci.com/task/5774349121617920

**Comment by fkorotkov** [comment]
@ibuclaw thank you! I've fixed the underlying host. The VM got corrupted.
