### ISSUE TITLE
Intermittent monterey-xcode-13.3 failures when starting up VMs

### ISSUE THREAD

**Issue by dkorpel** [cirruslabs/osx-images#45]
Similar to https://github.com/cirruslabs/osx-images/issues/43

> Persistent worker failed to start the task: Parallels isolation failed: failed to create VM cloned from "monterey-xcode-13.3": Parallels VM operation failed: failed to get info for VM with "monterey-xcode-13.3" UUID or name: Parallels command returned non-zero exit code: "Failed to get VM config: The virtual machine could not be found. The virtual machine is not registered in the virtual machine directory on your Mac."

Happens from time to time, for example:
https://cirrus-ci.com/task/4679658435248128

**Comment by fkorotkov** [comment]
Seems the `k16-1` worker got the VM corrupted. I've recreated it on the worker so now everything should be OK. Sorry for the inconviniences!
