### ISSUE TITLE
mojave-xcode-10.2 & mojave-flutter upgrades

### ISSUE THREAD

**Issue by ened** [cirruslabs/osx-images#8]
Xcode 10.2 has been released just now and includes a ABI stable version of Swift, 5.0.

Cirrus should support the new Xcode version & also update the flutter vm image.

**Comment by fkorotkov** [comment]
Waiting for it to appear [here](https://developer.apple.com/download/more/) so it can be installed through command-line.

**Comment by fkorotkov** [comment]
mojave-xcode-10.2 is now available 🙌

**Comment by ened** [comment]
Fantastic. Can we also create a mojave-flutter-xcode-10.2 image, to be somewhat sure it won't break builds for others..

**Comment by ened** [comment]
@fkorotkov thx for your help
